services:
  nginx:
    container_name: nginx
    image: nginx:42
    build: ./requirements/nginx/
    env_file: 
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
      - adminer:/var/www/html/adminer
    depends_on:
      wordpress:
        condition: service_healthy
      cadvisor:
        condition: service_healthy
      adminer:
        condition: service_healthy
      website:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: ./requirements/mariadb/
    env_file:
      - .env
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p$DB_ROOT_PASS"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    env_file:
      - .env
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pidof", "php-fpm83"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

  redis:
    container_name: redis
    image: redis:42
    build: ./requirements/bonus/redis/
    env_file:
      - .env
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pidof redis-server"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer:42
    build: ./requirements/bonus/adminer
    networks:
      - inception
    restart: always
    volumes:
      - adminer:/var/www/html/adminer
  cadvisor:
    container_name: cadvisor 
    build: ./requirements/bonus/cadvisor
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "pidof", "cadvisor"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  ftp:
    container_name: ftp 
    image: ftp:42
    build: ./requirements/bonus/ftp
    networks:
      - inception
    restart: always
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress:/srv/ftp/wordpress

  website:
    container_name: website 
    image: website:42
    build: ./requirements/bonus/website/
    networks:
      - inception
    healthcheck:
      test: ["CMD", "pidof", "python3"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
    restart: always


networks:
  inception:
    name: inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb 

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress  

  adminer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/adminer
