services:
  nginx:
    container_name: nginx
    build: ./src/requirements/nginx/
    env_file: 
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on: 
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./src/requirements/mariadb/
    env_file:
      - .env
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: ./src/requirements/wordpress/
    env_file:
      - .env
    depends_on: 
      - mariadb
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html

  redis:
    container_name: redis
    build: ./src/requirements/bonus/redis/
    env_file:
      - .env
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hibenouk/data/mariadb 

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hibenouk/data/wordpress  

