services:
  nginx:
    container_name: nginx
    build: ./src/requirements/nginx/
    env_file: 
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
      - adminer:/var/www/html/adminer
    depends_on: 
      - wordpress
      - adminer
      - cadvisor

  mariadb:
    container_name: mariadb
    build: ./src/requirements/mariadb/
    env_file:
      - .env
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./src/requirements/wordpress/
    env_file:
      - .env
    depends_on: 
      - mariadb
      - redis
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress

  redis:
    container_name: redis
    build: ./src/requirements/bonus/redis/
    env_file:
      - .env
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer
    build: ./src/requirements/bonus/adminer
    networks:
      - inception
    restart: always
    volumes:
      - adminer:/var/www/html/adminer

  cadvisor:
    container_name: cadvisor 
    build: ./src/requirements/bonus/cadvisor
    networks:
      - inception
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  ftp:
    container_name: ftp 
    build: ./src/requirements/bonus/ftp
    networks:
      - inception
    restart: always
    env_file:
    - .env
    ports:
      - "21:21"
      - "20:20"
      - "21000-21005:21000-21005"
    volumes:
      - wordpress:/var/www/html/wordpress

  website:
    container_name: website 
    build: ./src/requirements/bonus/website/
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hibenouk/data/mariadb 

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hibenouk/data/wordpress  

  adminer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hibenouk/data/adminer
